### ISSUE TITLE
Difference between OS=el and OS=centos

### ISSUE THREAD

**Issue by akopytov** [packpack/packpack#71]
I'm a little confused between `OS=el` and `OS=centos`. As I understand they both refer to the same OS (or the same docker image to be precise), but the names are used inconsistently. 

README.md examples use "el" and so do .travis.yml in Tarantool and packpack itself. But packpack-docker-images does not have any references to "el", it only uses "centos". Then https://hub.docker.com/r/packpack/packpack/tags/ contains both "el" and "centos" images. But only for x86, not for arrm.

What is not clear to me:
- is there any difference between "el" and "centos" docker images?
- how do the "el" images appear on the Docker Hub?
- what are the reasons for using `OS=el` instead of `OS=centos`?

I didn't even notice this inconsistency until I tried passing `OS=el DIST=7 ARCH=aarch64` to packpack.

**Comment by rtsisyk** [comment]
Initially we used "el" tag for CentOS images because PackageCloud supports only RHEL, Oracle Linux and Scientific Linux, but not CentOS. It was reasonable, because it simplified all scripts and `.travis.yml` (see `dist: ${OS}/${DIST}`).  

One day somebody realized that CentOS images were incorrectly named as "Enterprise Linux" and renamed them to "centos" to match the real situation. CentOS claims to be an independent project, but everybody know that CentOS is "RHEL for the poor". Now we have two completely identical images with different tags. 

Shall we eliminate name "centos" and use "el" everywhere?

**Comment by akopytov** [comment]
OK, so inconsistency comes from 1) how packagecloud names things (it only supports "EL" as an umbrella name for a variety of distributions) and 2) how people prefer to name their packages to better reflect their target distribution (like "centos").

Because of # 2, I don't think it's reasonable to enforce any specific naming (different people/projects may have different preferences in how packages are named).

What would probably make more sense for packpack is to accept arbitrary distribution names (more precisely, treat OS as a docker repo tag as it already does), then map them to packagecloud classification automatically. In fact, the "centos" -> "el" mapping is the only thing that comes to mind right now, but this can be extended in the future.

Does this sound like a good idea?

**Comment by rtsisyk** [comment]
> What would probably make more sense for packpack is to accept arbitrary distribution names (more precisely, treat OS as a docker repo tag as it already does), then map them to packagecloud classification automatically. In fact, the "centos" -> "el" mapping is the only thing that comes to mind right now, but this can be extended in the future.

The primary problem with this idea that PackPack itself doesn't upload to PackageCloud (the first version did, but lately I switched to PackageCloud deployment for Travis CI). PackageCloud deployment doesn't support "dist: centos/7", so we need to implement some sophisticated .travis.yml script...

```
deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: "${PACKAGECLOUD_USER}"
    repository: "${PACKAGECLOUD_REPO}"
    token: "${PACKAGECLOUD_TOKEN}"
    dist: "${OS}/${DIST}"
    package_glob: "${PACKAGECLOUD_GLOB}"
    skip_cleanup: true
    on:
      all_branches: true
condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
```
